### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by jesberpen** [brunocalado/scum-and-villainy-pt-br#1]
Hi, I couldn't find a way to contact you. I have a Spanish translation of this repository that I have created, I wanted to ask if it was ok for it to be published. You can see from my profile that I have never uploaded to git, so I'm not sure the best way to do this, I know a little bit about coding but I'm quite a newbe so not sure how to do it, either we can put the translation here with the rest of your files, or I can figure out how to create it separately.

**Comment by brunocalado** [comment]
Hi.

You need to create your on module.

You can use mine to make things easier. Duplicate it and rename for your work. Ex scum-and-villainy-espanish or something

**Comment by jesberpen** [comment]
Brilliant, thanks a lot, I'll make sure to mention this one as source :)
